name: riverpod_ecommerce
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  iconsax: ^0.0.8
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  flutter_riverpod: ^2.6.1
  dotted_line: ^3.2.3
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true

  assets:
    - .env